### ISSUE TITLE
Context Panel: No verse number/links

### ISSUE THREAD

**Issue by openbibles** [rubiot/ibiblia#65] opened 2019-07-16 05:10 UTC
Matt. 10:7, 14:32, Genesis 5:9,

**Comment by rubiot** [comment] 2019-08-18 15:14
I saw this once but I can't reproduce it. Can you reproduce it consistently using your project?

**Comment by openbibles** [comment] 2019-08-19 04:18
Hmmm...interesting because it all vanished last time I checked.

**Comment by rubiot** [comment] 2019-10-08 18:12
The new chapter view released yesterday is a completely new implementation, so it's unlikely that this bug still exists, therefore I'm closing it. If it pops up again, please reopen the issue.

**Closed by rubiot** 2019-10-08 18:12 UTC
Labels: bug
