### ISSUE TITLE
Feature Reques: Word Click to theWord lookup (Strongs plus)

### ISSUE THREAD

**Issue by jgkoehn** [rubiot/ibiblia#39] opened 2019-03-07 23:36 UTC
I appreciate the word lookup feature of iBiblia in regards to Strongs.
I may be missing something but could you call theWord lookup for the Actual Word, Lemma, and Morphology as well based on the iBiblia users choice and order of lookup. Very similar to theWord "word click"

**Comment by rubiot** [comment] 2019-03-08 01:07
I think this is a duplicate of request #31. Is that right?

**Comment by jgkoehn** [comment] 2019-03-08 01:08
Ah correct yes.

**Comment by rubiot** [comment] 2019-03-09 16:22
Duplicate of issue #31.

**Closed by rubiot** 2019-03-09 16:22 UTC
Labels: duplicate
