### ISSUE TITLE
Found a workaround if user wants to load a destination text with Strongs Tag without experiencing #20 and #5 issues

### ISSUE THREAD

**Issue by openbibles** [rubiot/ibiblia#24] opened 2019-01-21 06:15 UTC
I just did an experiment on how to load a tagged module into the destination text without getting #20 and #5. 
Test 1: I tried to replace my destination text with my tagged module into my existing .bib file. 
Result 1: Issue #20 and #5 happened much.
Test 2: I tried to create and setup a clean .bib project by selecting "New" under project menu. I used the same files I used in Test 1.
Result 2: No occurrence of  #20 and #5 and no existing association which is expected.
Probably we can add in the wiki that tagged modules can be imported into the destination text as long as its a new project setup.

**Comment by rubiot** [comment] 2019-01-21 15:24
OK. I think I know what the problem is: iBiblia is not clearing old associations when the user loads a new text. When it tries to apply the old associations the words don't align with the old text and it crashes. I'll fix that soon.

**Comment by rubiot** [comment] 2019-01-21 15:28
I have a question: What's the motivation for loading an already tagged text into the destination verse if iBiblia's purpose it to add those tags?

**Comment by openbibles** [comment] 2019-01-21 22:41
I think there is no need for it since iBiblia Merge Tool is already released. I used this workaround before seeing the merge tool and having found out that there are hundreds of extra spaces in my destination text that I removed using a word processor.

**Comment by rubiot** [comment] 2019-01-24 00:40
Fixed in the latest [release](https://github.com/rubiot/ibiblia/releases/tag/v1.0.0.50).

**Closed by rubiot** 2019-01-24 00:40 UTC
Labels: bug
